apiVersion: v1
kind: Pod
metadata:
  name: mysql-with-logger
  labels:
    app: mysql
spec:
  volumes:
    - name: mysql-logs
      emptyDir: {}   # shared volume for logs
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-logs
          mountPath: /var/log/mysql
      args:
        # redirect MySQL logs into the shared volume
        - "--log-error=/var/log/mysql/error.log"
        - "--general-log=1"
        - "--general-log-file=/var/log/mysql/general.log"

    - name: log-collector
      image: busybox
      command: ["/bin/sh","-c"]
      args: ["tail -F /var/log/mysql/error.log /var/log/mysql/general.log"]
      volumeMounts:
        - name: mysql-logs
          mountPath: /var/log/mysql
