apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:9.9-community
          env:
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://postgres:5432/sonarqube
            - name: SONAR_JDBC_USERNAME
              value: sonarqube
            - name: SONAR_JDBC_PASSWORD
              value: sonarqube
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "16Mi" 
              cpu: "50m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "2048Mi"
              cpu: "1000m"
